services:

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
    - '1883:1883'
    - '9001:9001'
    volumes:
    - './mosquitto2.conf:/mosquitto/config/mosquitto.conf'
    - 'mosquitto_data:/mosquitto/data'
    restart: always

volumes:
  mosquitto_data: