services: 
  temp-sensor:
    build:
      context: .
    # image: python:dht11
    privileged: true
    volumes:
    - './dht_11.py:/usr/src/myapp/dht_11.py'
    command: ['python3', './dht_11.py']

  web-server:
    build:
      context: .
    privileged: true
    ports: 
      - '8080:8080'
    volumes:
    - './:/usr/src/myapp/'
    command: ['python3', './webserver.py']
    
  light-sensor:
    build:
      context: .
    privileged: true
    volumes:
    - './light_sensor.py:/usr/src/myapp/light_sensor.py'
    command: ['python3', './light_sensor.py']

  