global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: [
        '172.17.0.1:9100',
        'maximilian:9100',
        'dragonpi:9100',
        'mondaymorning:9100'  
      ]
  - job_name: 'windows-exporter'
    static_configs:
      - targets: [
        'v-c104-01:9182',
        'v-c104-03:9182',
        'v-c104-08:9182'
      ]

  - job_name: 'sensors'
    static_configs:
      - targets: [
        '172.17.0.1:8080'
      ]